name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      firstword: Hi
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.modifiedfirstword }}
